---
version: '3'
services:
  runserver:
    image: runserver
    build: django
    ports:
      - '8000:8000'
    volumes:
      - ./django:/home/sid/app:z
      - filestorage:/home/sid/upload:z
      - filecache:/home/sid/cache:z
      - ./scripts/init_django.sh:/usr/bin/init_django.sh:z
    environment:
      - LANG=en_UK.utf8
      - LC_ALL=en_UK.UTF-8
      - LC_LANG=en_UK.UTF-8
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - HTTPS=off
      - DJANGO_SETTINGS_MODULE=local_settings_docker
      - POSTGRES_HOST=postgresql
      - POSTGRES_PASSWORD=gallery
      - POSTGRES_USER=gallery
      - POSTGRES_DB=gallery
      - FIXTURES=languagegallery/fixtures/assets.json
    networks:
      - network
    links:
      - postgresql
    depends_on:
      - postgresql
    stdin_open: true
    tty: true

  postgresql:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=gallery
      - POSTGRES_USER=gallery
      - POSTGRES_PASSWORD=gallery
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - network
    stdin_open: true
    tty: true

volumes:
  filestorage:
  filecache:
  postgresql:

networks:
  network:
