---
version: '3'
services:
  runserver:
    image: runserver
    build: django
    ports:
      - '8000:8000'
    volumes:
      - django:/home/sid/app
    links:
      - postgresql
    environment:
      - HTTPS=off
      - LANG=en_UK.utf8
      - LC_ALL=en_UK.UTF-8
      - LC_LANG=en_UK.UTF-8
      - PYTHONUNBUFFERED=1
      - GIT_AUTHOR_EMAIL
      - GIT_AUTHOR_NAME
      - GIT_COMMITTER_EMAIL
      - GIT_COMMITTER_NAME
    networks:
      - network
    depends_on:
      - postgresql
    stdin_open: true
    tty: true

  webapp:
    image: webapp
    build: react
    ports:
      - '3000:3000'
    volumes:
      - react:
    environment:
      - HTTPS=off
      - LANG=en_UK.utf8
      - LC_ALL=en_UK.UTF-8
      - LC_LANG=en_UK.UTF-8
    networks:
      - network
    depends_on:
      - runserver
    stdin_open: true
    tty: true

  postgresql:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=django
      - POSTGRES_USER=django
      - POSTGRES_DB=django
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - network

volumes:
  postgresql:

networks:
  network:
