# Generated by Django 2.0.13 on 2019-11-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.BinaryField(max_length=32, unique=True)),
                ('basename', models.CharField(max_length=50)),
                ('width', models.BigIntegerField(null=True)),
                ('height', models.BigIntegerField(null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='media')),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10)),
                ('mimetype', models.CharField(max_length=110)),
                ('extension', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='mimetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languagegallery.MimeType'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='tags',
            field=models.ManyToManyField(to='languagegallery.MediaTag'),
        ),
    ]
