# Generated by Django 3.1.7 on 2021-03-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languagegallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': 'file info', 'verbose_name_plural': 'file info'},
        ),
        migrations.AlterModelOptions(
            name='mediatag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='mimetype',
            options={'verbose_name': 'mimetype', 'verbose_name_plural': 'mimetypes'},
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='basename',
            field=models.CharField(max_length=50, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file',
            field=models.FileField(upload_to='media', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='height',
            field=models.BigIntegerField(null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='mimetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languagegallery.mimetype', verbose_name='mimetype'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='sha256',
            field=models.BinaryField(max_length=32, unique=True, verbose_name='checksum, SHA256'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='tags',
            field=models.ManyToManyField(related_name='files', to='languagegallery.MediaTag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails', verbose_name='thumbnails'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='width',
            field=models.BigIntegerField(null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='mediatag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mimetype',
            name='extension',
            field=models.CharField(max_length=10, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='mimetype',
            name='identifier',
            field=models.CharField(max_length=10, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='mimetype',
            name='mimetype',
            field=models.CharField(max_length=110, verbose_name='mimetype'),
        ),
    ]
