# Generated by Django 3.1.7 on 2021-03-02 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languagegallery', '0002_overall_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00 Z', verbose_name='uploaded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='uploader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='mediatag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00:00 Z', verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediatag',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='basename',
            field=models.CharField(max_length=200, verbose_name='basename'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='languagegallery.MediaTag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='mediatag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
